(()=>{var e={};e.id=165,e.ids=[165],e.modules={7849:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external")},5403:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external")},4749:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external")},399:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},5528:e=>{"use strict";e.exports=require("next/dist\\client\\components\\action-async-storage.external.js")},1877:e=>{"use strict";e.exports=require("next/dist\\client\\components\\request-async-storage.external.js")},5319:e=>{"use strict";e.exports=require("next/dist\\client\\components\\static-generation-async-storage.external.js")},1666:(e,t,n)=>{"use strict";n.r(t),n.d(t,{GlobalError:()=>i.a,__next_app__:()=>u,originalPathname:()=>h,pages:()=>d,routeModule:()=>g,tree:()=>l});var r=n(482),s=n(9108),o=n(2563),i=n.n(o),a=n(8300),c={};for(let e in a)0>["default","tree","pages","GlobalError","originalPathname","__next_app__","routeModule"].indexOf(e)&&(c[e]=()=>a[e]);n.d(t,c);let l=["",{children:["__PAGE__",{},{page:[()=>Promise.resolve().then(n.t.bind(n,9361,23)),"next/dist/client/components/not-found-error"]}]},{layout:[()=>Promise.resolve().then(n.bind(n,2054)),"C:\\Users\\Dev\\Documents\\Git\\PromotionLanding\\src\\app\\layout.tsx"],"not-found":[()=>Promise.resolve().then(n.t.bind(n,9361,23)),"next/dist/client/components/not-found-error"]}],d=[],h="/_not-found",u={require:n,loadChunk:()=>Promise.resolve()},g=new r.AppPageRouteModule({definition:{kind:s.x.APP_PAGE,page:"/_not-found",pathname:"/_not-found",bundlePath:"",filename:"",appPaths:[]},userland:{loaderTree:l}})},334:(e,t,n)=>{Promise.resolve().then(n.t.bind(n,2583,23)),Promise.resolve().then(n.t.bind(n,6840,23)),Promise.resolve().then(n.t.bind(n,8771,23)),Promise.resolve().then(n.t.bind(n,3225,23)),Promise.resolve().then(n.t.bind(n,9295,23)),Promise.resolve().then(n.t.bind(n,3982,23))},6245:(e,t,n)=>{Promise.resolve().then(n.t.bind(n,2704,23)),Promise.resolve().then(n.bind(n,6281))},6281:(e,t,n)=>{"use strict";n.r(t),n.d(t,{NavigationContext:()=>o,default:()=>i});var r=n(2295),s=n(3729);let o=(0,s.createContext)({activePage:"",navigateTo:()=>{}}),i=({children:e})=>{let[t,n]=(0,s.useState)("Home");return(0,s.useEffect)(()=>{window.location.href.includes("partner")?n("partner"):window.location.href.includes("howItWorks")?n("howItWorks"):n("home")},[]),r.jsx(o.Provider,{value:{activePage:t,navigateTo:e=>{n(e)}},children:e})}},2054:(e,t,n)=>{"use strict";n.r(t),n.d(t,{default:()=>m});var r=n(5036),s=n(3640),o=n.n(s);n(2),n(4315);var i=n(986),a=n(4825),c=n.n(a),l=n(6843);let d=(0,l.createProxy)(String.raw`C:\Users\Dev\Documents\Git\PromotionLanding\src\contexts\navegationContext.tsx`),{__esModule:h,$$typeof:u}=d,g=d.default;function m({children:e}){let t=`
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3852209,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
  `,n=`
  window.dataLayer = window.dataLayer || []
  function gtag(){dataLayer.push(arguments)}
  gtag('js', new Date())
  gtag('config', 'G-TDJSD87QN1')
  `;return(0,r.jsxs)("html",{lang:"pt-br",children:[(0,r.jsxs)("head",{children:[r.jsx("title",{children:"MarcaNutri"}),r.jsx("link",{rel:"preconnect",href:"https://fonts.googleapis.com"}),r.jsx("link",{rel:"preconnect",href:"https://fonts.gstatic.com"}),r.jsx("link",{href:"https://fonts.googleapis.com/css2?family=Jomhuria&family=Nunito+Sans:opsz,wght@6..12,300;6..12,400;6..12,600;6..12,700&family=Roboto:wght@400;500;700&display=swap",rel:"stylesheet"}),r.jsx("link",{rel:"icon",type:"image/x-icon",href:"./favicon.ico"})]}),(0,r.jsxs)("body",{className:o().className,children:[r.jsx(g,{children:e}),r.jsx(c(),{strategy:"afterInteractive",dangerouslySetInnerHTML:{__html:t}}),r.jsx("script",{async:!0,src:"https://www.googletagmanager.com/gtag/js?id=G-TDJSD87QN1"}),r.jsx(c(),{dangerouslySetInnerHTML:{__html:n}})]})]})}(0,l.createProxy)(String.raw`C:\Users\Dev\Documents\Git\PromotionLanding\src\contexts\navegationContext.tsx#NavigationContext`),i.Z.init(3852209,6)},4315:()=>{}};var t=require("../webpack-runtime.js");t.C(e);var n=e=>t(t.s=e),r=t.X(0,[638,58],()=>n(1666));module.exports=r})();